# Generated by Django 3.1.3 on 2021-01-11 12:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votingbooth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ballot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hashed_vote', models.CharField(max_length=128)),
                ('Date_voted', models.DateField(blank=True, default=datetime.datetime.now)),
                ('Election_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votingbooth.election')),
                ('Voter_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
