# Generated by Django 3.1.3 on 2020-11-18 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField(max_length=256)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('Owner_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(max_length=64)),
                ('Result', models.IntegerField(default=0)),
                ('Answer_date', models.DateField()),
                ('Election_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votingbooth.election')),
            ],
        ),
    ]
